### ISSUE TITLE
Regarding Green Lines

### ISSUE THREAD

**Issue by icedterminal** [icedterminal/syshelp#1] opened 2021-03-22 09:01 UTC
@54601

I didn't know how else to get in touch with you. You have no information in your profile. I got around to looking at the linked thread in your open issue for Jellyfin. Rather than clog up the open issues over on Jellyfin, I thought I would tag you to reach out to you.

It's known QSV has issues with XVID. After more reading, it appears QSV has some other special requirements or quirks. At least according to ffmpegs bug tracker. As such this means a certain aspect is under user control. Here is that developers comment:

> *Use `-extra_hw_frames` to set an initial pool size.*
> *There are ideas about making this happen automatically, but the problem is that we don't have enough negotiation between components to know how big the pool should be - if it's feeding into a scaler then probably 2 or 3 frames are sufficient, but if it's feeding into an encoder with lookahead enabled then you might need over 100. As such, it's currently under user control.*

I played around with various formats of media and the available encoders I have. As I stated in your open issue, QSV is the only one to show green lines. It's likely ffmpeg blames Intel for this. Since AMD and Nvidia do not do this. So this isn't Jellyfins fault. A solution, per the ffmpeg developers comment, is not implemented and likely won't be. That said, the suggested fix in that linked open issue shows

> `hwupload=extra_hw_frames=64`

I'm not sure how that user got that number. Now I googled that string, `extra_hw_frames`, to see what other people were using in all kinds of scenarios. Not just Jellyfin. Numbers are all over the place.

I downloaded the 10.7.1 release code and changed the file:
> jellyfin/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs

Grabbed the suggested code snippet:
```
            else if (((isLinux && hasGraphicalSubs && !(isTonemappingSupportedOnQsv && isVppTonemappingSupported))
                || isSwDecoder) && (isQsvH264Encoder || isQsvHevcEncoder))
```

Saved changes and built it for my platform: Ubuntu x64, native. The only file needed, was `MediaBrowser.Controller.dll`.  I copied that over the install on my system. Here are the results:

| 10.7.1 Release | 10.7.1 with changed DLL |
| --- | --- |
| ![release](https://i.imgur.com/gy9PgfF.png) | ![debug](https://i.imgur.com/gyT8wDX.png) |

Problem solved. The change has been committed to a branch of Jellyfin here: https://github.com/jellyfin/jellyfin/blob/d100b2d902480e37d6a52abe80a4013622b666af/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs - So it's not in the mainline version yet. It could be peer reviewed some more. Whether or not that change sticks is up to the Jellyfin contributors. For now, if you wish, I built the Windows x64 DLL for you to use. Just replace the existing one with the one I have attatched.

[MediaBrowser.Controller.zip](https://github.com/icedterminal/syshelp/files/6180761/MediaBrowser.Controller.zip)

**Comment by 54601** [comment] 2021-03-22 15:55
Thank you so much! There’s just no way I can describe my gratitude. I have download the file and I will test it as so as I get home. I will describe the results in my previous issue. Thank again.

发送自 Windows 10 版邮件应用

发件人: icedterminal
发送时间: 2021年3月22日 17:01
收件人: icedterminal/syshelp
抄送: 54601; Mention
主题: [icedterminal/syshelp] Regarding Green Lines (#1)

@54601
I didn't know how else to get in touch with you. You have no information in your profile. I got around to looking at the linked thread in your open issue for Jellyfin. Rather than clog up the open issues over on Jellyfin, I thought I would tag you to reach out to you.
It's known QSV has issues with XVID. After more reading, it appears QSV has some other special requirements or quirks. At least according to ffmpegs bug tracker. As such this means a certain aspect is under user control. Here is that developers comment:
Use -extra_hw_frames to set an initial pool size.
There are ideas about making this happen automatically, but the problem is that we don't have enough negotiation between components to know how big the pool should be - if it's feeding into a scaler then probably 2 or 3 frames are sufficient, but if it's feeding into an encoder with lookahead enabled then you might need over 100. As such, it's currently under user control.
I played around with various formats of media and the available encoders I have. As I stated in your open issue, QSV is the only one to show green lines. It's likely ffmpeg blames Intel for this. Since AMD and Nvidia do not do this. So this isn't Jellyfins fault. A solution, per the ffmpeg developers comment, is not implemented and likely won't be. That said, the suggested fix in that linked open issue shows
hwupload=extra_hw_frames=64
I'm not sure how that user got that number. Now I googled that string, extra_hw_frames, to see what other people were using in all kinds of scenarios. Not just Jellyfin. Numbers are all over the place.
I downloaded the 10.7.1 release code and changed the file:
jellyfin/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs
Grabbed the suggested code snippet:
            else if (((isLinux && hasGraphicalSubs && !(isTonemappingSupportedOnQsv && isVppTonemappingSupported))
                || isSwDecoder) && (isQsvH264Encoder || isQsvHevcEncoder))
Saved changes and built it for my platform: Ubuntu x64, native. The only file needed, was MediaBrowser.Controller.dll. I copied that over the install on my system. Here are the results:
10.7.1 Release
10.7.1 with changed DLL


Problem solved. The change has been committed to a branch of Jellyfin here: https://github.com/jellyfin/jellyfin/blob/d100b2d902480e37d6a52abe80a4013622b666af/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs - So it's not in the mainline version yet. It could be peer reviewed some more. Whether or not that change sticks is up to the Jellyfin contributors. For now, if you wish, I built the Windows x64 DLL for you to use. Just replace the existing one with the one I have attatched.
MediaBrowser.Controller.zip

**Comment by icedterminal** [comment] 2021-03-23 01:16
> Thank you so much! There’s just no way I can describe my gratitude. I have download the file and I will test it as so as I get home. I will describe the results in my previous issue. Thank again. 

You should definitely thank the other user who linked that issue with a possible fix. Without that comment, wouldn't have known otherwise. I saw you commented asking if there was anything you could do on your end. I didn’t know if you were comfortable with building from source (IMO it’s easy). In any case I wanted to share the results with you. It’s no fun having media look corrupted.

Learned something new.

**Comment by 54601** [comment] 2021-03-23 05:34
> > Thank you so much! There’s just no way I can describe my gratitude. I have download the file and I will test it as so as I get home. I will describe the results in my previous issue. Thank again.
> 
> You should definitely thank the other user who linked that issue with a possible fix. Without that comment, wouldn't have known otherwise. I saw you commented asking if there was anything you could do on your end. I didn’t know if you were comfortable with building from source (IMO it’s easy). In any case I wanted to share the results with you. It’s no fun having media look corrupted.
> 
> Learned something new.

Yeah, this community is great, being very nice to beginners. I tried as you suggested at home and it worked most marvelously. The green lines problem is fixed.

**Closed** 2021-04-03 21:35 UTC

**Comment by icedterminal** [comment] 2021-04-12 13:46
10.7.2 does not include the fix as I suspected. It's still being held in a development branch. I'll need to rebuild the DLL for this version.

**Comment by icedterminal** [comment] 2021-05-06 05:29
10.7.5 does not include a fix. Rebuilt including a fix.

[MediaBrowser.Controller.zip](https://github.com/icedterminal/syshelp/files/6431954/MediaBrowser.Controller.zip)
